### ISSUE TITLE
Roadmap 🙃

### ISSUE THREAD

**Issue by s0lus** [MyOwnStar/platformer#6]
- [ ] Create more levels
- [ ] Create transitions between levels
- [ ] Create some simple GUI (HP/Current level/etc.)
- [ ] Enemy simple AI
